### PR TITLE
Fix CaseObjectHashCode script

### PR DESCRIPTION
**Pull request by ShapelessCat**

### CODE REVIEW

**Comment by ShapelessCat** [comment]
Also, should we use Scala's hash code function `.##` here instead of Java's `.hashCode`?
`.##` handles Java boxed values differently.
```scala
import java.lang.{Integer as I, Double as D}

val boxedInteger1 = I.valueOf(1)
val boxedDouble1 = D.valueOf(1.0)

boxedInteger1 == boxedDouble1        // true
boxedInteger1 equals boxedDouble1  // false

boxedInteger1.hashCode   // 1
boxedInteger1.##               // 1

boxedDouble1.hashCode  // 1072693248
boxedDouble1.##              // 1
```

In Scala's hash-based data structures, the method `.##` is used:
```scala
val mp = HashMap(d1 -> 3, 1 -> 4)
// val mp: HashMap[Matchable, Int] = HashMap(1.0 -> 4)
```
If `.hashCode` was used, this hash-map should include two key-value pairs.

**Comment by ShapelessCat** [comment]
I also created a typo report for the second commit of this PR through https://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920365686.

**Review by deanwampler — APPROVED** [review]
Thanks for catching these typos!

**Comment by deanwampler** [comment]
Apparently `##` behaves differently from `hashCode` for boxed value types and `null`: https://dotty.epfl.ch/api/scala/Any.html###-0

**Comment by ShapelessCat** [comment]
> Apparently `##` behaves differently from `hashCode` for boxed value types and `null`: https://dotty.epfl.ch/api/scala/Any.html###-0

I mean, in the first paragraph of the section "Case Objects and hashCode", you write
"The notion of equality goes hand in hand with the results of hashing an object, as done by `hashCode`, which is used in hash-based data structures, like the default `Map` and `Set` implementations."

This sentence is correct, but do you think there can be a new footnote to mention `##`? Because of the usages of `##`, we have this:
```scala
val mp = HashMap(d1Boxed -> 3, 1 -> 4)
// val mp: HashMap[Matchable, Int] = HashMap(1.0 -> 4)
```
If people don't know `##`, they may think Scala hash-based data structures use `hashCode` directly, then if they didn't try some code, they may think the result of `val mp = HashMap(d1Boxed -> 3, 1 -> 4)` contains two key-value pairs.

**Comment by deanwampler-domino** [comment]
I'll consider a footnote that recommends reading the scaladoc for `##`, but the different behavior is an edge case. Most people will let `Map` and other tools call whatever hash code method on keys it wants to use internally. As long as the same method is used consistently, the results will be consistent. Also, it will be very rare for people use Java wrappers around doubles in Scala code. The behavior for `null` is also different, but using `null` in any context where a hash code will be computed is an application bug anyway.

**Pull request merged**
